// ============================================================================
// Volt Defense — Master Configuration
// Single source of truth for ALL game constants, buildings, enemies, waves.
// ============================================================================

var Config = {

    // ------------------------------------------------------------------------
    // General
    // ------------------------------------------------------------------------
    VERSION: '0.8.0',
    TICK_RATE: 100,             // ms per tick
    TICKS_PER_SECOND: 10,

    // Map & viewport
    MAP_WIDTH: 10000,
    MAP_HEIGHT: 10000,
    GRID_CELL_SIZE: 40,
    VIEWPORT_WIDTH: Math.min(window.innerWidth || 1920, 1920),
    VIEWPORT_HEIGHT: Math.min(window.innerHeight || 1080, 1080),

    // Day/Night & Wind
    DAY_NIGHT_CYCLE: 24,        // seconds for full cycle (12s day, 12s night)
    WIND_CHANGE_INTERVAL: 24,   // seconds between wind speed changes
    WIND_MAX_SPEED: 30,         // mph max
    WIND_BASELINE_SPEED: 15,    // mph where turbines produce rated output

    // Cables
    CABLE_MAX_LENGTH: 200,
    CABLE_MAX_PER_BUILDING: 4,
    CABLE_MAX_THROUGHPUT: 50,
    CABLE_COST: 25,
    HC_CABLE_MAX_THROUGHPUT: 500,
    HC_CABLE_COST_PER_TILE: 50,

    // Placement
    MAX_PLACEMENT_DISTANCE: 200,

    // Hydro
    HYDRO_CURRENT_REDUCTION: 0.15,
    MIN_CURRENT_SPEED: 0.05,

    // Consumer battery
    CONSUMER_BATTERY_SELL_PRICE: 1500,

    // Laser
    LASER_RAMP_INTERVAL: 1.0,
    LASER_ARMOR_BYPASS: 0.5,

    // Missile
    MISSILE_HOMING_ANGLE: 20,
    MISSILE_MAX_RANGE_MULT: 1.5,

    // Blaster
    BLASTER_HOMING_ANGLE: 30,
    BLASTER_MAX_RANGE_MULT: 1.3,

    // Fusion Beam
    FUSION_RAMP_INTERVAL: 0.33,  // ramps 3x faster than lasers
    FUSION_ARMOR_BYPASS: 0.8,    // pierces most armor

    // Shield
    SHIELD_DIAMETER: 400,
    SHIELD_POWER_DRAIN_ON_HIT: 50,
    SHIELD_PASSIVE_DRAIN: 0,
    SHIELD_DECAY_RATE: 0.1,

    // Pollution
    POLLUTION_PASSIVE_DECAY: 0.1,           // per tick
    POLLUTION_THRESHOLD_LOW: 50,
    POLLUTION_THRESHOLD_MODERATE: 150,
    POLLUTION_THRESHOLD_HIGH: 300,
    POLLUTION_THRESHOLD_CRITICAL: 500,
    POLLUTION_ENEMY_SPEED_BOOST_MOD: 0.10,
    POLLUTION_ENEMY_SPEED_BOOST_HIGH: 0.20,
    POLLUTION_ENERGY_PENALTY_CRITICAL: 0.20,

    // Workers
    WORKER_RECRUIT_INTERVAL: 30,            // ticks
    WORKER_RECRUIT_AMOUNT: 1,
    WORKER_HOMELESS_GRACE: 300,             // ticks
    WORKER_DEPART_INTERVAL_HIGH: 100,       // ticks
    WORKER_DEPART_INTERVAL_CRITICAL: 50,    // ticks

    // Waves
    FIRST_WAVE_DELAY: 180,                  // seconds
    WAVE_INTERVAL: 120,                      // seconds
    WAVE_COMPLETION_BASE: 281,
    WAVE_COMPLETION_SCALE: 56,

    // Starting resources
    START_MONEY: 2000,
    START_COAL: 50,
    CORE_HP: 100,
    SELL_REFUND_RATIO: 0.5,

    // ------------------------------------------------------------------------
    // Terrain Types
    // ------------------------------------------------------------------------
    TERRAIN_TYPES: {
        grass: 0,
        rock: 1,
        water: 2,
        deep_water: 3,
        bridge: 4,
        iron_deposit: 10,
        coal_deposit: 11,
        uranium_deposit: 12,
        oil_deposit: 13
    },

    // ------------------------------------------------------------------------
    // Buildings
    // ------------------------------------------------------------------------
    BUILDINGS: {

        // ---- Power --------------------------------------------------------
        solar: {
            name: 'Solar Panel',
            category: 'power',
            cost: { money: 300 },
            size: [1, 1],
            hp: 60,
            workersRequired: 1,
            energyGeneration: 12,
            energyConsumption: 0,
            energyStorageCapacity: 0,
            maxChargeRate: 0,
            maxDischargeRate: 0,
            pollution: 0,
            upgradeTo: null,
            description: 'Generates 12 energy during daytime only. No output at night.',
            icon: '☀️'
        },
        wind: {
            name: 'Wind Turbine',
            category: 'power',
            cost: { money: 250 },
            size: [1, 1],
            hp: 50,
            workersRequired: 1,
            energyGeneration: 10,
            energyConsumption: 0,
            energyStorageCapacity: 0,
            maxChargeRate: 0,
            maxDischargeRate: 0,
            pollution: 0,
            variability: 0.2,
            upgradeTo: null,
            description: 'Generates 0-20 energy based on wind speed (10 at 15 mph).',
            icon: '🌀'
        },
        coal_plant: {
            name: 'Coal Plant',
            category: 'power',
            cost: { money: 500 },
            size: [2, 2],
            hp: 120,
            workersRequired: 3,
            energyGeneration: 64,
            energyConsumption: 0,
            energyStorageCapacity: 0,
            maxChargeRate: 0,
            maxDischargeRate: 0,
            pollution: 0.3,
            fuelCost: { coal: 2 },
            fuelInterval: 10,           // ticks
            upgradeTo: 'gas_plant',
            description: 'Reliable 64 energy. Burns 2 coal every 10 ticks. Pollutes.',
            icon: '🏭'
        },
        gas_plant: {
            name: 'Gas Plant',
            category: 'power',
            cost: { money: 800 },
            size: [2, 2],
            hp: 100,
            workersRequired: 3,
            energyGeneration: 80,
            energyConsumption: 0,
            energyStorageCapacity: 0,
            maxChargeRate: 0,
            maxDischargeRate: 0,
            pollution: 0.2,
            fuelCost: { oil: 1 },
            fuelInterval: 10,
            upgradeTo: null,
            description: 'Upgraded plant. 80 energy, burns oil for fuel.',
            icon: '🏗️'
        },
        nuclear_plant: {
            name: 'Nuclear Plant',
            category: 'power',
            cost: { money: 5000, iron: 100, steel: 50 },
            size: [2, 2],
            hp: 200,
            workersRequired: 8,
            energyGeneration: 240,
            energyConsumption: 0,
            energyStorageCapacity: 0,
            maxChargeRate: 0,
            maxDischargeRate: 0,
            pollution: 0.1,
            fuelCost: { uranium: 1 },
            fuelInterval: 50,
            upgradeTo: null,
            description: 'Massive 240 energy output. Requires uranium fuel.',
            icon: '☢️'
        },
        hydro_plant: {
            name: 'Hydro Plant',
            category: 'power',
            cost: { money: 600 },
            size: [1, 1],
            hp: 80,
            workersRequired: 2,
            energyGeneration: 24,
            energyConsumption: 0,
            energyStorageCapacity: 0,
            maxChargeRate: 0,
            maxDischargeRate: 0,
            pollution: 0,
            requiresTerrain: 'water',
            upgradeTo: null,
            description: 'Generates up to 24 energy, scaled by water current speed.',
            icon: '🌊'
        },

        // ---- Storage ------------------------------------------------------
        small_battery: {
            name: 'Small Battery',
            category: 'storage',
            cost: { money: 200 },
            size: [1, 1],
            hp: 60,
            workersRequired: 1,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 500,
            maxChargeRate: 15,
            maxDischargeRate: 20,
            pollution: 0,
            upgradeTo: 'large_battery',
            description: 'Stores 500 energy. Steady charge/discharge.',
            icon: '🔋'
        },
        large_battery: {
            name: 'Large Battery',
            category: 'storage',
            cost: { money: 800 },
            size: [1, 1],
            hp: 80,
            workersRequired: 1,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 2000,
            maxChargeRate: 35,
            maxDischargeRate: 40,
            pollution: 0,
            upgradeTo: null,
            description: 'Stores 2000 energy with faster throughput.',
            icon: '🔋'
        },
        capacitor: {
            name: 'Capacitor',
            category: 'storage',
            cost: { money: 600 },
            size: [1, 1],
            hp: 40,
            workersRequired: 1,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 200,
            maxChargeRate: 200,
            maxDischargeRate: 200,
            pollution: 0,
            upgradeTo: 'advanced_capacitor',
            description: 'Low capacity but extremely fast charge/discharge.',
            icon: '⚡'
        },
        advanced_capacitor: {
            name: 'Advanced Capacitor',
            category: 'storage',
            cost: { money: 2000 },
            size: [1, 1],
            hp: 60,
            workersRequired: 1,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 600,
            maxChargeRate: 600,
            maxDischargeRate: 600,
            pollution: 0,
            upgradeTo: null,
            description: 'High-performance capacitor with 3x capacity and charge/discharge rate.',
            icon: '⚡⚡'
        },
        consumer_battery: {
            name: 'Consumer Battery',
            category: 'consumer',
            cost: { money: 400 },
            size: [1, 1],
            hp: 60,
            workersRequired: 1,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 3750,
            maxChargeRate: 50,
            maxDischargeRate: 0,
            pollution: 0,
            sellPrice: 1500,
            upgradeTo: null,
            description: 'Charge to full and sell for $1500. Cannot discharge.',
            icon: '💰'
        },

        // ---- Mining -------------------------------------------------------
        iron_miner: {
            name: 'Iron Miner',
            category: 'mining',
            cost: { money: 400 },
            size: [1, 1],
            hp: 80,
            workersRequired: 2,
            energyGeneration: 0,
            energyConsumption: 15,
            energyStorageCapacity: 30,
            maxChargeRate: 30,
            maxDischargeRate: 0,
            pollution: 0,
            requiresTerrain: 'iron_deposit',
            extractionRate: 1,
            upgradeTo: 'iron_miner_t2',
            description: 'Extracts 1 iron per cycle from iron deposits.',
            icon: '⛏️'
        },
        iron_miner_t2: {
            name: 'Iron Miner T2',
            category: 'mining',
            cost: { money: 900, iron: 30 },
            size: [1, 1],
            hp: 120,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 25,
            energyStorageCapacity: 50,
            maxChargeRate: 50,
            maxDischargeRate: 0,
            pollution: 0,
            requiresTerrain: 'iron_deposit',
            extractionRate: 2.5,
            upgradeTo: null,
            description: 'Advanced iron miner. Extracts 2.5 iron per cycle.',
            icon: '⛏️'
        },
        coal_miner: {
            name: 'Coal Miner',
            category: 'mining',
            cost: { money: 350 },
            size: [1, 1],
            hp: 80,
            workersRequired: 2,
            energyGeneration: 0,
            energyConsumption: 15,
            energyStorageCapacity: 30,
            maxChargeRate: 30,
            maxDischargeRate: 0,
            pollution: 0,
            requiresTerrain: 'coal_deposit',
            extractionRate: 1,
            upgradeTo: 'coal_miner_t2',
            description: 'Extracts 1 coal per cycle from coal deposits.',
            icon: '⛏️'
        },
        coal_miner_t2: {
            name: 'Coal Miner T2',
            category: 'mining',
            cost: { money: 800 },
            size: [1, 1],
            hp: 120,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 25,
            energyStorageCapacity: 50,
            maxChargeRate: 50,
            maxDischargeRate: 0,
            pollution: 0,
            requiresTerrain: 'coal_deposit',
            extractionRate: 2.5,
            upgradeTo: null,
            description: 'Advanced coal miner. Extracts 2.5 coal per cycle.',
            icon: '⛏️'
        },
        uranium_miner: {
            name: 'Uranium Miner',
            category: 'mining',
            cost: { money: 1000, iron: 100 },
            size: [1, 1],
            hp: 100,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 30,
            energyStorageCapacity: 60,
            maxChargeRate: 60,
            maxDischargeRate: 0,
            pollution: 0,
            requiresTerrain: 'uranium_deposit',
            extractionRate: 0.5,
            upgradeTo: 'uranium_miner_t2',
            description: 'Extracts 0.5 uranium per cycle. Expensive but essential.',
            icon: '☢️'
        },
        uranium_miner_t2: {
            name: 'Uranium Miner T2',
            category: 'mining',
            cost: { money: 2500, iron: 200 },
            size: [1, 1],
            hp: 150,
            workersRequired: 4,
            energyGeneration: 0,
            energyConsumption: 50,
            energyStorageCapacity: 100,
            maxChargeRate: 100,
            maxDischargeRate: 0,
            pollution: 0,
            requiresTerrain: 'uranium_deposit',
            extractionRate: 1.2,
            upgradeTo: null,
            description: 'Advanced uranium miner. Extracts 1.2 uranium per cycle.',
            icon: '☢️'
        },

        oil_drill: {
            name: 'Oil Drill',
            category: 'mining',
            cost: { money: 500 },
            size: [1, 1],
            hp: 80,
            workersRequired: 2,
            energyGeneration: 0,
            energyConsumption: 15,
            energyStorageCapacity: 30,
            maxChargeRate: 30,
            maxDischargeRate: 0,
            pollution: 0.1,
            requiresTerrain: 'oil_deposit',
            extractionRate: 1,
            upgradeTo: 'oil_drill_t2',
            description: 'Extracts 1 oil per cycle from oil deposits.',
            icon: '🛢️'
        },
        oil_drill_t2: {
            name: 'Oil Drill T2',
            category: 'mining',
            cost: { money: 1000, iron: 40 },
            size: [1, 1],
            hp: 120,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 25,
            energyStorageCapacity: 50,
            maxChargeRate: 50,
            maxDischargeRate: 0,
            pollution: 0.15,
            requiresTerrain: 'oil_deposit',
            extractionRate: 2.5,
            upgradeTo: null,
            description: 'Advanced oil drill. Extracts 2.5 oil per cycle.',
            icon: '🛢️'
        },

        smelter: {
            name: 'Smelter',
            category: 'mining',
            cost: { money: 800, iron: 30 },
            size: [1, 1],
            hp: 100,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 7,
            energyStorageCapacity: 20,
            maxChargeRate: 15,
            maxDischargeRate: 0,
            pollution: 0.3,
            smeltInput: { iron: 4, coal: 2 },
            smeltOutput: { steel: 2 },
            smeltInterval: 120,
            upgradeTo: null,
            description: 'Converts 4 iron + 2 coal into 2 steel every 12 seconds. Requires energy.',
            icon: '🔥⚙️'
        },

        // ---- Weapons ------------------------------------------------------
        laser_t1: {
            name: 'Laser Turret T1',
            category: 'weapons',
            cost: { money: 500 },
            size: [1, 1],
            hp: 80,
            workersRequired: 2,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 135,
            maxChargeRate: 100,
            maxDischargeRate: 0,
            pollution: 0,
            baseDPS: 5,
            range: 300,
            baseEnergyDraw: 30,
            maxRamp: 8,
            upgradeTo: 'laser_t2',
            description: 'Continuous beam. DPS ramps up the longer it fires.',
            icon: '🔴'
        },
        laser_t2: {
            name: 'Laser Turret T2',
            category: 'weapons',
            cost: { money: 1500 },
            size: [1, 1],
            hp: 100,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 270,
            maxChargeRate: 200,
            maxDischargeRate: 0,
            pollution: 0,
            baseDPS: 12,
            range: 400,
            baseEnergyDraw: 60,
            maxRamp: 8,
            buildable: false,
            upgradeTo: 'laser_t3',
            description: 'Upgraded laser. Higher DPS and longer range.',
            icon: '🔴'
        },
        laser_t3: {
            name: 'Laser Turret T3',
            category: 'weapons',
            cost: { money: 4000 },
            size: [1, 1],
            hp: 120,
            workersRequired: 5,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 675,
            maxChargeRate: 300,
            maxDischargeRate: 0,
            pollution: 0,
            baseDPS: 25,
            range: 500,
            baseEnergyDraw: 100,
            maxRamp: 16,
            buildable: false,
            upgradeTo: null,
            description: 'Top-tier laser. Devastating sustained damage.',
            icon: '🔴'
        },
        missile_t1: {
            name: 'Missile Launcher T1',
            category: 'weapons',
            cost: { money: 400, iron: 50 },
            size: [1, 1],
            hp: 80,
            workersRequired: 2,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 150,
            maxChargeRate: 50,
            maxDischargeRate: 0,
            pollution: 0,
            damage: 40,
            range: 500,
            energyPerShot: 50,
            reloadTicks: 20,
            ironPerShot: 1,
            missileSpeed: 300,
            upgradeTo: 'missile_t2',
            description: 'Fires homing missiles. Costs iron per shot.',
            icon: '🚀'
        },
        missile_t2: {
            name: 'Missile Launcher T2',
            category: 'weapons',
            cost: { money: 1200, iron: 100 },
            size: [1, 1],
            hp: 100,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 120,
            maxChargeRate: 100,
            maxDischargeRate: 0,
            pollution: 0,
            damage: 100,
            range: 650,
            energyPerShot: 100,
            reloadTicks: 25,
            ironPerShot: 2,
            missileSpeed: 350,
            buildable: false,
            upgradeTo: 'missile_t3',
            description: 'Upgraded missiles. Higher damage and range.',
            icon: '🚀'
        },
        missile_t3: {
            name: 'Missile Launcher T3',
            category: 'weapons',
            cost: { money: 3000, iron: 200 },
            size: [1, 1],
            hp: 120,
            workersRequired: 4,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 100,
            maxChargeRate: 200,
            maxDischargeRate: 0,
            pollution: 0,
            damage: 250,
            range: 800,
            energyPerShot: 150,
            reloadTicks: 30,
            ironPerShot: 3,
            missileSpeed: 400,
            buildable: false,
            upgradeTo: null,
            description: 'Heavy missiles. Devastating single-target damage.',
            icon: '🚀'
        },

        blaster_t1: {
            name: 'Blaster T1',
            category: 'weapons',
            cost: { money: 200 },
            size: [1, 1],
            hp: 70,
            workersRequired: 2,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 120,
            maxChargeRate: 80,
            maxDischargeRate: 0,
            pollution: 0,
            damage: 10,
            range: 250,
            energyPerShot: 20,
            reloadTicks: 5,
            projectileSpeed: 400,
            upgradeTo: 'blaster_t2',
            description: 'Rapid-fire energy blaster. Shoots every 0.5s with good accuracy.',
            icon: '🔵'
        },
        blaster_t2: {
            name: 'Blaster T2',
            category: 'weapons',
            cost: { money: 800 },
            size: [1, 1],
            hp: 90,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 300,
            maxChargeRate: 150,
            maxDischargeRate: 0,
            pollution: 0,
            damage: 20,
            range: 400,
            energyPerShot: 50,
            reloadTicks: 5,
            projectileSpeed: 500,
            buildable: false,
            upgradeTo: 'blaster_t3',
            description: 'Upgraded blaster. More damage and range.',
            icon: '🔵'
        },
        blaster_t3: {
            name: 'Blaster T3',
            category: 'weapons',
            cost: { money: 2000 },
            size: [1, 1],
            hp: 110,
            workersRequired: 4,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 600,
            maxChargeRate: 250,
            maxDischargeRate: 0,
            pollution: 0,
            damage: 40,
            range: 600,
            energyPerShot: 100,
            reloadTicks: 5,
            projectileSpeed: 600,
            buildable: false,
            upgradeTo: null,
            description: 'Top-tier blaster. Devastating rapid fire.',
            icon: '🔵'
        },

        tesla_coil: {
            name: 'Tesla Coil',
            category: 'weapons',
            cost: { money: 800 },
            size: [1, 1],
            hp: 80,
            workersRequired: 2,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 150,
            maxChargeRate: 150,
            maxDischargeRate: 0,
            pollution: 0,
            baseDamage: 11,
            range: 250,
            energyDraw: 50,
            chainCount: 3,
            chainRange: 150,
            chainDecay: 0.7,
            upgradeTo: null,
            description: 'Chain lightning hits closest enemy and jumps to up to 3 more within 150px, dealing 70% damage per jump.',
            icon: '⚡'
        },

        flamethrower: {
            name: 'Flamethrower',
            category: 'weapons',
            cost: { money: 600, oil: 30 },
            size: [1, 1],
            hp: 70,
            workersRequired: 2,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 60,
            maxChargeRate: 80,
            maxDischargeRate: 0,
            pollution: 0,
            baseDPS: 8,
            range: 150,
            energyDraw: 20,
            oilPerTick: 0.1,
            burnDPS: 3,
            burnDuration: 30,
            upgradeTo: null,
            description: 'Short-range AoE that damages all enemies in range. Burns 1 oil per 10 ticks while firing. Applies burning DOT: 3 DPS for 3 seconds.',
            icon: '🔥'
        },

        railgun: {
            name: 'Railgun',
            category: 'weapons',
            cost: { money: 2000, iron: 100 },
            size: [1, 1],
            hp: 90,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 375,
            maxChargeRate: 250,
            maxDischargeRate: 0,
            pollution: 0,
            damage: 100,
            range: 800,
            energyPerShot: 250,
            reloadTicks: 40,
            ironPerShot: 3,
            upgradeTo: null,
            description: 'Piercing shot damages all enemies in a line. Long range, high damage.',
            icon: '🔫'
        },

        emp_tower: {
            name: 'EMP Tower',
            category: 'weapons',
            cost: { money: 1500, iron: 50 },
            size: [1, 1],
            hp: 100,
            workersRequired: 2,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 1500,
            maxChargeRate: 200,
            maxDischargeRate: 0,
            pollution: 0,
            range: 400,
            energyPerActivation: 500,
            cooldownTicks: 100,
            stunDuration: 50,
            upgradeTo: null,
            description: 'Stuns all enemies in range for 5 seconds. High energy cost per activation.',
            icon: '📡'
        },

        mortar: {
            name: 'Mortar',
            category: 'weapons',
            cost: { money: 700, iron: 40 },
            size: [1, 1],
            hp: 80,
            workersRequired: 2,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 200,
            maxChargeRate: 100,
            maxDischargeRate: 0,
            pollution: 0,
            damage: 60,
            range: 600,
            minRange: 100,
            energyPerShot: 200,
            reloadTicks: 30,
            ironPerShot: 2,
            splashRadius: 80,
            mortarSpeed: 200,
            upgradeTo: null,
            description: 'Lobs explosive shells. Splash damage hits all enemies within 80px radius. Cannot fire at close range.',
            icon: '💥'
        },

        drone_bay: {
            name: 'Drone Bay',
            category: 'weapons',
            cost: { money: 2500, iron: 150 },
            size: [1, 1],
            hp: 120,
            workersRequired: 4,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 1000,
            maxChargeRate: 200,
            maxDischargeRate: 0,
            pollution: 0,
            maxDrones: 3,
            droneSpawnTicks: 240,
            droneIronCost: 20,
            droneEnergyCost: 500,
            droneHP: 50,
            droneDPS: 24,
            droneSpeed: 120,
            droneRange: 500,
            droneLifetime: 600,
            upgradeTo: null,
            description: 'Spawns autonomous drones that seek and destroy enemies. Max 3 active drones.',
            icon: '🛸'
        },

        // ---- Steel Weapons --------------------------------------------------
        mine_layer: {
            name: 'Mine Layer',
            category: 'weapons',
            cost: { money: 600, steel: 15 },
            size: [1, 1],
            hp: 90,
            workersRequired: 2,
            energyGeneration: 0,
            energyConsumption: 5,
            energyStorageCapacity: 30,
            maxChargeRate: 15,
            maxDischargeRate: 0,
            pollution: 0,
            maxMines: 10,
            mineGenerateTicks: 240,
            mineSteelCost: 5,
            mineDamage: 150,
            mineSplashRadius: 60,
            mineRadius: 200,
            range: 200,
            upgradeTo: null,
            description: 'Deploys up to 10 proximity mines in a circle. Each mine takes 24s and 5 steel to generate. Mines deal 150 splash damage.',
            icon: '💣'
        },
        autocannon: {
            name: 'Autocannon',
            category: 'weapons',
            cost: { money: 1400, steel: 35 },
            size: [1, 1],
            hp: 100,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 200,
            maxChargeRate: 150,
            maxDischargeRate: 0,
            pollution: 0,
            damage: 30,
            range: 400,
            energyPerShot: 15,
            reloadTicks: 3,
            steelPerBurst: 1,
            burstShotCount: 5,
            projectileSpeed: 500,
            upgradeTo: null,
            description: 'Fast-firing ballistic weapon. 30 dmg every 0.3s. Consumes 1 steel per 5 shots.',
            icon: '🔫'
        },

        // ---- Uranium Weapons --------------------------------------------------
        plasma_cannon: {
            name: 'Plasma Cannon',
            category: 'weapons',
            cost: { money: 3000, uranium: 20 },
            size: [1, 1],
            hp: 100,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 500,
            maxChargeRate: 300,
            maxDischargeRate: 0,
            pollution: 0,
            range: 500,
            damage: 500,
            energyPerShot: 250,
            uraniumPerShot: 1,
            reloadTicks: 15,
            armorBypass: 1.0,
            upgradeTo: null,
            description: 'Fires superheated plasma bolts that ignore all enemy armor. Uses uranium fuel rods.',
            icon: '🔮'
        },
        fusion_beam: {
            name: 'Fusion Beam',
            category: 'weapons',
            cost: { money: 5000, uranium: 50, iron: 80 },
            size: [2, 2],
            hp: 150,
            workersRequired: 5,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 360,
            maxChargeRate: 500,
            maxDischargeRate: 0,
            pollution: 0,
            range: 1200,
            baseDPS: 25,
            energyDraw: 60,
            uraniumPerSecond: 0.5,
            upgradeTo: null,
            description: 'Ultra-long-range continuous beam. Ramps 3x faster than lasers, ignores most armor. Consumes uranium.',
            icon: '⚛️'
        },

        // ---- Defense ------------------------------------------------------
        shield_t1: {
            name: 'Shield Generator T1',
            category: 'defense',
            cost: { money: 1500, iron: 50 },
            size: [2, 2],
            hp: 150,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 20,
            energyStorageCapacity: 500,
            maxChargeRate: 100,
            maxDischargeRate: 0,
            pollution: 0,
            shieldHP: 500,
            shieldDiameter: 400,
            shieldEnergyCostPerDamage: 50,
            upgradeTo: 'shield_t2',
            description: 'Projects a shield dome. Drains energy when hit.',
            icon: '🛡️'
        },
        shield_t2: {
            name: 'Shield Generator T2',
            category: 'defense',
            cost: { money: 4000, steel: 50 },
            size: [2, 2],
            hp: 250,
            workersRequired: 5,
            energyGeneration: 0,
            energyConsumption: 40,
            energyStorageCapacity: 1000,
            maxChargeRate: 200,
            maxDischargeRate: 0,
            pollution: 0,
            shieldHP: 1200,
            shieldDiameter: 560,
            shieldEnergyCostPerDamage: 40,
            upgradeTo: null,
            description: 'Upgraded shield. More HP, range, and efficient energy use.',
            icon: '🛡️'
        },

        // ---- Housing ------------------------------------------------------
        small_house: {
            name: 'Small House',
            category: 'housing',
            cost: { money: 150 },
            size: [1, 1],
            hp: 60,
            workersRequired: 0,
            workersHoused: 4,
            energyGeneration: 0,
            energyConsumption: 3,
            energyStorageCapacity: 75,
            maxChargeRate: 10,
            maxDischargeRate: 0,
            pollution: 0,
            upgradeTo: 'medium_house',
            description: 'Houses 4 workers. Requires a small amount of power.',
            icon: '🏠'
        },
        medium_house: {
            name: 'Medium House',
            category: 'housing',
            cost: { money: 500 },
            size: [1, 1],
            hp: 80,
            workersRequired: 0,
            workersHoused: 12,
            energyGeneration: 0,
            energyConsumption: 7,
            energyStorageCapacity: 170,
            maxChargeRate: 15,
            maxDischargeRate: 0,
            pollution: 0,
            upgradeTo: 'large_house',
            description: 'Houses 12 workers. Moderate power draw.',
            icon: '🏘️'
        },
        large_house: {
            name: 'Large House',
            category: 'housing',
            cost: { money: 1200, iron: 30 },
            size: [2, 2],
            hp: 120,
            workersRequired: 0,
            workersHoused: 30,
            energyGeneration: 0,
            energyConsumption: 14,
            energyStorageCapacity: 340,
            maxChargeRate: 25,
            maxDischargeRate: 0,
            pollution: 0,
            upgradeTo: null,
            description: 'Houses 30 workers. Efficient large-scale housing.',
            icon: '🏢'
        },

        // ---- Environment --------------------------------------------------
        carbon_collector_t1: {
            name: 'Carbon Collector T1',
            category: 'environment',
            cost: { money: 800 },
            size: [1, 1],
            hp: 60,
            workersRequired: 2,
            energyGeneration: 0,
            energyConsumption: 25,
            energyStorageCapacity: 100,
            maxChargeRate: 60,
            maxDischargeRate: 0,
            pollution: 0,
            pollutionReduction: 2,
            upgradeTo: 'carbon_collector_t2',
            description: 'Reduces pollution by 2 per tick. Power-hungry.',
            icon: '🌿'
        },
        carbon_collector_t2: {
            name: 'Carbon Collector T2',
            category: 'environment',
            cost: { money: 2000, iron: 50 },
            size: [2, 2],
            hp: 100,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 50,
            energyStorageCapacity: 200,
            maxChargeRate: 120,
            maxDischargeRate: 0,
            pollution: 0,
            pollutionReduction: 5,
            upgradeTo: null,
            description: 'Reduces pollution by 5 per tick. Very power-hungry.',
            icon: '🌳'
        },

        // ---- Grid ---------------------------------------------------------
        pylon: {
            name: 'Pylon',
            category: 'grid',
            cost: { money: 50 },
            size: [1, 1],
            hp: 50,
            workersRequired: 0,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 10,
            maxChargeRate: 50,
            maxDischargeRate: 50,
            pollution: 0,
            upgradeTo: 'hc_pylon',
            description: 'Relay node. Extends cable network cheaply.',
            icon: '📡'
        },
        water_pylon: {
            name: 'Water Pylon',
            category: 'grid',
            cost: { money: 200 },
            size: [1, 1],
            hp: 50,
            workersRequired: 0,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 10,
            maxChargeRate: 50,
            maxDischargeRate: 50,
            pollution: 0,
            requiresWater: true,
            upgradeTo: null,
            description: 'Relay node for water tiles. Extends cable network across rivers.',
            icon: '🌊'
        },
        hc_pylon: {
            name: 'HC Pylon',
            category: 'grid',
            cost: { money: 400 },
            size: [1, 1],
            hp: 60,
            workersRequired: 0,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 50,
            maxChargeRate: 500,
            maxDischargeRate: 500,
            maxCableConnections: 6,
            pollution: 0,
            upgradeTo: null,
            description: 'High-capacity relay. 500 energy/tick throughput, 6 cable connections.',
            icon: '⚡'
        },
        core: {
            name: 'Core',
            category: 'grid',
            cost: { money: 0 },
            size: [2, 2],
            hp: 100,
            workersRequired: 0,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 500,
            maxChargeRate: 500,
            maxDischargeRate: 500,
            maxCableConnections: 8,
            pollution: 0,
            upgradeTo: 'core_armored',
            buildable: false,
            description: 'Your base. If this falls, you lose. Acts as a high-capacity energy relay.',
            icon: '⚫'
        },
        core_armored: {
            name: 'Armored Core',
            category: 'grid',
            cost: { money: 5000, steel: 100 },
            size: [2, 2],
            hp: 100,
            workersRequired: 0,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 500,
            maxChargeRate: 500,
            maxDischargeRate: 500,
            maxCableConnections: 8,
            pollution: 0,
            damageReduction: 0.10,
            upgradeTo: null,
            buildable: false,
            description: 'Reinforced core with steel plating. All damage reduced by 10%.',
            icon: '🛡️⚫'
        },
        grid_connect: {
            name: 'Consumer Grid Connect',
            category: 'consumer',
            cost: { money: 250 },
            size: [1, 1],
            hp: 60,
            workersRequired: 1,
            energyGeneration: 0,
            energyConsumption: 8,
            energyStorageCapacity: 50,
            maxChargeRate: 20,
            maxDischargeRate: 0,
            pollution: 0,
            moneyPerSecond: 4,
            upgradeTo: null,
            description: 'Sells power to the consumer grid. Slowly earns $4/s while powered.',
            icon: '🔌'
        },
        consumer_market: {
            name: 'Consumer Market',
            category: 'consumer',
            cost: { money: 500 },
            size: [1, 1],
            hp: 80,
            workersRequired: 1,
            energyGeneration: 0,
            energyConsumption: 3,
            energyStorageCapacity: 20,
            maxChargeRate: 10,
            maxDischargeRate: 0,
            pollution: 0,
            sellInterval: 120,
            resourcePrices: { coal: 10, iron: 20, oil: 25, steel: 60, uranium: 100 },
            upgradeTo: null,
            description: 'A marketplace that sells your resources for profit. Toggle which resources to sell. Sells one of each enabled resource every 12 seconds.',
            icon: '🏪'
        },

        // ---- Defense (Wall) -----------------------------------------------
        wall: {
            name: 'Wall',
            category: 'defense',
            cost: { money: 50, iron: 1 },
            size: [1, 1],
            hp: 200,
            workersRequired: 0,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 0,
            maxChargeRate: 0,
            maxDischargeRate: 0,
            pollution: 0,
            noCables: true,
            upgradeTo: null,
            description: 'Blocks enemy movement. Enemies must path around or destroy it.',
            icon: '🧱'
        },
        electric_wall: {
            name: 'Electric Wall',
            category: 'defense',
            cost: { money: 300, iron: 2 },
            size: [1, 1],
            hp: 200,
            workersRequired: 0,
            energyGeneration: 0,
            energyConsumption: 2,
            energyStorageCapacity: 10,
            maxChargeRate: 5,
            maxDischargeRate: 0,
            pollution: 0,
            contactDamage: 2,
            upgradeTo: null,
            description: 'Electrified wall that deals 2 damage/s to enemies attacking it. Requires energy.',
            icon: '⚡🧱'
        },
        steel_wall: {
            name: 'Steel Wall',
            category: 'defense',
            cost: { money: 200, steel: 2 },
            size: [1, 1],
            hp: 500,
            workersRequired: 0,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 0,
            maxChargeRate: 0,
            maxDischargeRate: 0,
            pollution: 0,
            noCables: true,
            upgradeTo: null,
            description: 'Reinforced steel wall with 500 HP. Much tougher than standard walls.',
            icon: '🔩🧱'
        },
        core_repair: {
            name: 'Core Repair',
            category: 'defense',
            cost: { money: 10000, steel: 100, uranium: 50 },
            size: [1, 1],
            hp: 150,
            workersRequired: 3,
            energyGeneration: 0,
            energyConsumption: 0,
            energyStorageCapacity: 10000,
            maxChargeRate: 50,
            maxDischargeRate: 0,
            pollution: 0,
            requiresAdjacentCore: true,
            maxCount: 3,
            upgradeTo: null,
            description: 'Repairs the core by 1 HP when fully charged (10,000 energy). Must be placed adjacent to core. Max 3.',
            icon: '🔧'
        }
    },

    // ------------------------------------------------------------------------
    // Enemies
    // ------------------------------------------------------------------------
    ENEMIES: {
        spark: {
            name: 'Spark',
            hp: 20,
            speed: 80,
            damage: 3,
            armor: 0,
            killReward: 10,
            scoreValue: 1,
            icon: '⚡',
            special: null,
            firstWave: 1,
            description: 'The most basic hostile entity drawn to your grid\'s energy signature. Sparks are small, fast-moving charges that zip toward your core in erratic bursts. Individually weak, they test your early defenses and punish gaps in coverage. They have no armor and low HP, but in later waves they arrive in overwhelming numbers. Targets the core directly.'
        },
        runner: {
            name: 'Runner',
            hp: 15,
            speed: 140,
            damage: 3,
            armor: 0,
            killReward: 16,
            scoreValue: 3,
            icon: '💨',
            special: null,
            firstWave: 2,
            description: 'Lightning-fast entities that prioritize speed over durability. Runners streak across the map at nearly double the speed of a Spark, slipping past slow-tracking weapons before they can lock on. They have no armor but their raw velocity makes them dangerous — a cluster of Runners can reach your core before your defenses react. Best countered with fast-firing weapons or area denial. Targets the core directly.'
        },
        grunt: {
            name: 'Grunt',
            hp: 80,
            speed: 60,
            damage: 7,
            armor: 2,
            killReward: 24,
            scoreValue: 6,
            icon: '👹',
            special: null,
            firstWave: 3,
            description: 'The backbone of enemy forces. Grunts are tough, moderately armored soldiers that march steadily toward your core. With 80 HP and 2 armor, they can absorb significant punishment from low-tier weapons. They deal respectable damage and serve as the "standard" threat that all your defenses should be calibrated against. Targets the core directly.'
        },
        shielded_grunt: {
            name: 'Shielded Grunt',
            hp: 80,
            speed: 55,
            damage: 7,
            armor: 6,
            killReward: 36,
            scoreValue: 12,
            icon: '🛡️',
            special: null,
            firstWave: 6,
            description: 'An upgraded Grunt equipped with heavy plating. With 6 armor, Shielded Grunts drastically reduce incoming damage from low-tier weapons — you\'ll need higher-damage weapons or sustained laser fire to cut through their defenses. Slightly slower than regular Grunts but far more durable. They often appear mixed in with other enemies, soaking hits while lighter units slip through. Targets the core directly.'
        },
        wall_breaker: {
            name: 'Wall Breaker',
            hp: 150,
            speed: 65,
            damage: 20,
            armor: 4,
            killReward: 50,
            scoreValue: 15,
            icon: '🔨',
            special: 'targets_walls',
            wallsToDestroy: 3,
            firstWave: 7,
            description: 'A demolition specialist that ignores your core and instead targets your defensive walls. Wall Breakers deal devastating 60 damage per hit and will smash through up to 3 wall segments before resuming their path to the core. With 150 HP and 4 armor, they\'re sturdy enough to survive initial fire. Prioritize taking them down before they carve holes in your perimeter. Targets walls first, then the core.'
        },
        bomber: {
            name: 'Bomber',
            hp: 120,
            speed: 70,
            damage: 27,
            armor: 3,
            killReward: 100,
            scoreValue: 18,
            icon: '💣',
            special: 'targets_power',
            firstWave: 4,
            description: 'A cunning saboteur that bypasses your core entirely and heads straight for your power plants. Bombers deal 40 damage — enough to cripple or destroy undefended generators. Losing power plants cascades through your entire grid, starving weapons, shields, and batteries of energy. High kill reward reflects the threat they pose. Always keep weapon coverage near your power infrastructure. Targets power plants.'
        },
        tank: {
            name: 'Tank',
            hp: 350,
            speed: 30,
            damage: 20,
            armor: 8,
            killReward: 160,
            scoreValue: 22,
            icon: '🐢',
            special: null,
            firstWave: 10,
            description: 'A slow-moving behemoth with massive HP and heavy armor. Tanks crawl across the battlefield at only 30 speed, but their 350 HP and 8 armor make them extremely difficult to take down with anything less than a focused laser or sustained missile barrage. They tie up your defenses for a long time, allowing faster enemies in the same wave to slip past. Targets the core directly.'
        },
        emp_drone: {
            name: 'EMP Drone',
            hp: 50,
            speed: 110,
            damage: 0,
            armor: 0,
            killReward: 30,
            scoreValue: 8,
            icon: '🤖',
            special: 'emp_disable',
            firstWave: 13,
            description: 'A fragile but infuriating support unit that deals no physical damage. Instead, EMP Drones emit a disabling pulse that temporarily shuts down nearby buildings, cutting power generation and weapon fire. With 110 speed and 50 HP, they\'re hard to catch but easy to kill — if you can target them before they reach your infrastructure. Deploy fast-tracking weapons near key buildings. Disables buildings with EMP pulse.'
        },
        swarm: {
            name: 'Swarm',
            hp: 15,
            speed: 100,
            damage: 2,
            armor: 0,
            killReward: 6,
            scoreValue: 2,
            icon: '🐝',
            special: 'flying',
            firstWave: 16,
            description: 'Tiny, disposable units that attack in massive numbers. Each individual Swarm entity has only 15 HP and 2 damage, but they spawn in huge groups that overwhelm single-target weapons like lasers. Area-effect weapons like mortars and tesla coils excel against Swarms. Their low kill reward means they\'re not profitable to fight — they exist purely to drain your ammunition and energy. Targets the core directly.'
        },
        heavy_tank: {
            name: 'Heavy Tank',
            hp: 800,
            speed: 20,
            damage: 33,
            armor: 12,
            killReward: 160,
            scoreValue: 30,
            icon: '🦏',
            special: null,
            firstWave: 20,
            description: 'The ultimate conventional threat. Heavy Tanks boast a staggering 800 HP and 12 armor, rendering most basic weapons nearly useless against them. At 20 speed they\'re glacially slow, but their 50 damage per hit will tear through any building they reach. You\'ll need high-tier lasers with full damage ramp or concentrated missile fire to bring one down. Targets the core directly.'
        },
        saboteur: {
            name: 'Saboteur',
            hp: 60,
            speed: 90,
            damage: 5,
            armor: 0,
            killReward: 40,
            scoreValue: 10,
            icon: '🕵️',
            special: 'targets_grid',
            firstWave: 25,
            description: 'A stealthy operative that targets your power grid infrastructure and energy reserves. Saboteurs are fast and fragile, slipping through your defenses to sever critical energy connections and drain batteries. With only 5 damage and 60 HP, they\'re easy to kill — but if they reach a cable, pylon, or battery, they can disconnect entire sections of your grid or destroy your stored energy. Keep your grid interior defended. Targets cables, pylons, and batteries.'
        },
        siege_engine: {
            name: 'Siege Engine',
            hp: 1500,
            speed: 12,
            damage: 100,
            armor: 18,
            killReward: 400,
            scoreValue: 40,
            icon: '🏰',
            special: null,
            firstWave: 30,
            description: 'A colossal war machine that defines late-game threats. With 1500 HP, 18 armor, and 100 damage, Siege Engines are virtually invincible to conventional weapons. Only fully-ramped T3 lasers or fusion beams can reliably damage them through their massive armor. At 12 speed they move at a crawl, giving you time to focus fire — but if one reaches your core, it\'s devastating. Targets the core directly.'
        },
        phase_walker: {
            name: 'Phase Walker',
            hp: 200,
            speed: 70,
            damage: 10,
            armor: 0,
            killReward: 100,
            scoreValue: 25,
            icon: '👻',
            special: 'ignores_shields',
            firstWave: 40,
            description: 'An ethereal entity that phases through shield barriers as if they don\'t exist. Phase Walkers completely bypass your shield generators, making traditional chokepoint defenses useless against them. With 200 HP and no armor, they\'re vulnerable to direct weapon fire, but their shield-ignoring ability forces you to maintain weapon coverage behind your shield lines. Ignores all shields.'
        },
        jammer: {
            name: 'Jammer',
            hp: 150,
            speed: 50,
            damage: 7,
            armor: 5,
            killReward: 70,
            scoreValue: 22,
            icon: '📡',
            special: 'reduces_range',
            firstWave: 50,
            description: 'An electronic warfare specialist that emits a powerful interference field. All weapons within range of a Jammer have their effective targeting range significantly reduced, creating blind spots in your defense network. At 150 HP and 5 armor, they\'re moderately tough, and their support effect makes them a high-priority target. Kill Jammers first to restore your weapons\' full reach. Reduces nearby weapon range.'
        },
        river_serpent: {
            name: 'River Serpent',
            hp: 100,
            speed: 90,
            damage: 13,
            armor: 2,
            killReward: 50,
            scoreValue: 10,
            icon: '🐍',
            special: 'river_spawn',
            firstWave: 6,
            description: 'An aquatic predator that spawns directly from rivers on the map, bypassing your land-based perimeter entirely. River Serpents slither along waterways toward your core at high speed, emerging from unexpected angles. They\'re especially dangerous to undefended hydro plants built along rivers. Place weapons near river paths to intercept them. Spawns from rivers.'
        },
        home_wrecker: {
            name: 'Home Wrecker',
            hp: 150,
            speed: 65,
            damage: 20,
            armor: 4,
            killReward: 60,
            scoreValue: 14,
            icon: '🏚️',
            special: 'targets_housing',
            firstWave: 8,
            description: 'A vindictive enemy that specifically targets your housing buildings. Destroying houses eliminates your worker capacity, which can prevent you from staffing critical buildings like weapons and power plants. With 150 HP and 30 damage, Home Wreckers can demolish a small house in seconds. Protect your residential areas or risk a cascading workforce crisis. Targets housing buildings.'
        },
        drill_worm: {
            name: 'Drill Worm',
            hp: 120,
            speed: 55,
            damage: 17,
            armor: 3,
            killReward: 55,
            scoreValue: 12,
            icon: '🪱',
            special: 'targets_mining',
            firstWave: 10,
            description: 'A burrowing creature that surfaces near your mining operations and attacks miners directly. Drill Worms threaten your resource income by destroying the extractors that supply iron, coal, and uranium. With 120 HP and 25 damage, they can take out unguarded miners quickly. Always keep at least one weapon covering your mining sites. Targets mining buildings.'
        },
        disruptor: {
            name: 'Disruptor',
            hp: 100,
            speed: 75,
            damage: 13,
            armor: 2,
            killReward: 65,
            scoreValue: 15,
            icon: '💥',
            special: 'targets_weapons',
            firstWave: 12,
            description: 'A tactical threat that seeks out and destroys your weapon emplacements. Disruptors target lasers, missiles, mortars, tesla coils, and EMP towers — the very buildings you rely on to stop enemies. Losing a key weapon at the wrong moment can cause a cascade of breaches. Position redundant defenses and guard your weapons with walls or shields. Targets weapon buildings.'
        },
        leech: {
            name: 'Leech',
            hp: 80,
            speed: 70,
            damage: 10,
            armor: 1,
            killReward: 55,
            scoreValue: 12,
            icon: '🔋',
            special: 'targets_storage',
            firstWave: 14,
            description: 'An energy parasite that drains and destroys your batteries and capacitors. Leeches target energy storage buildings, depleting your reserves and reducing your grid\'s ability to buffer power for high-demand weapons like lasers and shields. At 80 HP and 1 armor they\'re fragile, but the economic damage of losing a full battery is severe. Targets energy storage buildings.'
        },
        nullifier: {
            name: 'Nullifier',
            hp: 180,
            speed: 50,
            damage: 27,
            armor: 5,
            killReward: 80,
            scoreValue: 20,
            icon: '🚫',
            special: 'targets_shields',
            firstWave: 18,
            description: 'An anti-shield specialist that homes in on your shield generators with single-minded focus. Nullifiers deal 35 damage and have enough HP and armor to survive sustained fire while they dismantle your barriers. Once a shield goes down, everything behind it becomes vulnerable. They often arrive alongside other enemies who exploit the gap. Targets shield generators.'
        },
        overload_boss: {
            name: 'Overload Boss',
            hp: 3000,
            speed: 25,
            damage: 67,
            armor: 15,
            killReward: 1000,
            scoreValue: 50,
            icon: '⚡👑',
            special: 'boss',
            firstWave: 20,
            isBoss: true,
            description: 'The first true boss enemy — a massive, crackling entity of pure overloaded energy. With 3000 HP, 15 armor, and 80 damage, the Overload Boss is a supreme test of your entire defense network. It moves slowly but absorbs enormous punishment, requiring your best weapons at full ramp to take down. The $1000 kill reward is well-earned. Prepare everything you have. Boss enemy — targets the core.'
        },
        scout_drone: {
            name: 'Scout Drone',
            hp: 40,
            speed: 120,
            damage: 5,
            armor: 0,
            killReward: 25,
            scoreValue: 5,
            icon: '🛸',
            special: 'flying',
            firstWave: 14,
            description: 'A lightweight aerial drone that flies directly toward your core, ignoring walls and ground obstacles entirely. Scout Drones are fast but fragile with only 40 HP and no armor. They bypass your maze-like wall defenses, forcing you to place weapons with clear firing lines rather than relying on chokepoints alone. Shields still block them. Flying enemy — ignores walls and buildings.'
        },
        heavy_flyer: {
            name: 'Heavy Flyer',
            hp: 250,
            speed: 35,
            damage: 20,
            armor: 5,
            killReward: 120,
            scoreValue: 25,
            icon: '🛩️',
            special: 'flying',
            firstWave: 19,
            description: 'A large, slow-moving aerial unit with substantial health and armor. Heavy Flyers cruise above your defenses in a straight line to the core, shrugging off light weapons with 250 HP and 5 armor. They are less durable than ground tanks but completely ignore your wall layout. Shields can still block them. Requires focused fire from multiple weapons. Flying enemy — ignores walls and buildings.'
        },
        tunneler: {
            name: 'Tunneler',
            hp: 130,
            speed: 50,
            damage: 17,
            armor: 4,
            killReward: 55,
            scoreValue: 13,
            icon: '⛏️',
            special: 'burrows',
            firstWave: 15,
            description: 'A burrowing enemy that digs underneath your walls as if they don\'t exist. Tunnelers pathfind normally around buildings but pass straight through wall segments, rendering your defensive perimeter useless against them. With 130 HP and 4 armor they\'re moderately tough. Place weapons behind your walls to catch them emerging on the other side. Burrows under walls.'
        },
        zapper: {
            name: 'Zapper',
            hp: 40,
            speed: 85,
            damage: 1,
            armor: 0,
            killReward: 20,
            scoreValue: 7,
            icon: '⚡',
            special: 'ranged_attack',
            mechanic: 'ranged_attack',
            rangedType: 'zapper',
            attackRange: 300,
            attackCooldown: 4,
            firstWave: 17,
            description: 'A fragile ranged attacker that fires weak electric bolts at the nearest building from 300 pixels away. Zappers deal only 1 damage per shot every 4 seconds, but they stay at range where your melee-only defenses can\'t touch them. In groups, their sustained fire adds up. Weapons with long range are needed to eliminate them before they whittle down your structures. Ranged attacker — targets closest building.'
        },
        plasma_parasite: {
            name: 'Plasma Parasite',
            hp: 100,
            speed: 65,
            damage: 10,
            armor: 2,
            killReward: 45,
            scoreValue: 14,
            icon: '🦠',
            special: 'ranged_attack',
            mechanic: 'ranged_attack',
            rangedType: 'plasma_parasite',
            attackRange: 100,
            attackCooldown: 1,
            energyDrain: 10,
            energyThreshold: 1000,
            chargedSpeed: 280,
            chargedDamage: 10,
            firstWave: 21,
            description: 'A horrifying energy parasite that latches onto nearby batteries, capacitors, and weapons from 100 pixels away, draining 10 energy per second. Plasma Parasites deal no physical damage — instead they siphon your stored power. Once they absorb 1000 energy, they become supercharged, doubling in speed and rushing the core with devastating force. Kill them before they feed. Drains energy from storage and weapons.'
        },
        emp_sniper: {
            name: 'EMP Sniper',
            hp: 90,
            speed: 40,
            damage: 10,
            armor: 3,
            killReward: 70,
            scoreValue: 18,
            icon: '🎯',
            special: 'ranged_attack',
            mechanic: 'ranged_attack',
            rangedType: 'emp_sniper',
            attackRange: 500,
            attackCooldown: 10,
            empDuration: 50,
            firstWave: 27,
            description: 'A deadly long-range specialist that fires EMP missiles from 500 pixels away. Each shot deals 10 damage and disables the target building for 5 seconds, cutting off power generation, weapon fire, or shield coverage. EMP Snipers are slow and moderately armored, preferring to hang back and systematically cripple your infrastructure. They target batteries, capacitors, shields, and power plants. Ranged EMP attacker — disables buildings.'
        }
    },

    // ------------------------------------------------------------------------
    // Wave Definitions (1–50)
    // ------------------------------------------------------------------------
    WAVES: [
        // Wave 1: Intro
        { number: 1, enemies: [{ type: 'spark', count: 3 }], spawnDelay: 800, spawnPoints: 1 },
        // Wave 2
        { number: 2, enemies: [{ type: 'spark', count: 5 }, { type: 'runner', count: 2 }], spawnDelay: 700, spawnPoints: 1 },
        // Wave 3
        { number: 3, enemies: [{ type: 'grunt', count: 3 }, { type: 'spark', count: 4 }], spawnDelay: 600, spawnPoints: 1 },
        // Wave 4: Bombers arrive (target power plants)
        { number: 4, enemies: [{ type: 'grunt', count: 4 }, { type: 'bomber', count: 2 }, { type: 'runner', count: 3 }], spawnDelay: 600, spawnPoints: 1 },
        // Wave 5
        { number: 5, enemies: [{ type: 'grunt', count: 6 }, { type: 'bomber', count: 2 }, { type: 'runner', count: 5 }], spawnDelay: 500, spawnPoints: 1 },
        // Wave 6: River Serpents + Shielded Grunts
        { number: 6, enemies: [{ type: 'shielded_grunt', count: 3 }, { type: 'river_serpent', count: 2 }, { type: 'grunt', count: 5 }], spawnDelay: 500, spawnPoints: 1 },
        // Wave 7: Wall Breakers arrive
        { number: 7, enemies: [{ type: 'wall_breaker', count: 2 }, { type: 'grunt', count: 8 }, { type: 'runner', count: 5 }, { type: 'shielded_grunt', count: 3 }, { type: 'bomber', count: 2 }], spawnDelay: 450, spawnPoints: 1 },
        // Wave 8: Home Wreckers arrive (target housing)
        { number: 8, enemies: [{ type: 'home_wrecker', count: 2 }, { type: 'grunt', count: 6 }, { type: 'river_serpent', count: 2 }, { type: 'runner', count: 4 }], spawnDelay: 450, spawnPoints: 2 },
        // Wave 9
        { number: 9, enemies: [{ type: 'shielded_grunt', count: 5 }, { type: 'bomber', count: 3 }, { type: 'home_wrecker', count: 2 }, { type: 'spark', count: 8 }], spawnDelay: 400, spawnPoints: 2 },
        // Wave 10: Drill Worms + Tank (target mines)
        { number: 10, enemies: [{ type: 'tank', count: 2 }, { type: 'drill_worm', count: 3 }, { type: 'grunt', count: 8 }, { type: 'river_serpent', count: 3 }], spawnDelay: 400, spawnPoints: 2 },
        // Wave 11
        { number: 11, enemies: [{ type: 'tank', count: 2 }, { type: 'wall_breaker', count: 4 }, { type: 'bomber', count: 4 }, { type: 'home_wrecker', count: 3 }, { type: 'shielded_grunt', count: 5 }, { type: 'drill_worm', count: 3 }], spawnDelay: 380, spawnPoints: 2 },
        // Wave 12: Disruptors arrive (target weapons)
        { number: 12, enemies: [{ type: 'disruptor', count: 3 }, { type: 'tank', count: 3 }, { type: 'grunt', count: 10 }, { type: 'runner', count: 8 }], spawnDelay: 380, spawnPoints: 2 },
        // Wave 13: EMP Drones join
        { number: 13, enemies: [{ type: 'emp_drone', count: 4 }, { type: 'disruptor', count: 3 }, { type: 'bomber', count: 4 }, { type: 'shielded_grunt', count: 7 }], spawnDelay: 360, spawnPoints: 2 },
        // Wave 14: Leeches + Scout Drones arrive (first flying enemy)
        { number: 14, enemies: [{ type: 'leech', count: 3 }, { type: 'scout_drone', count: 5 }, { type: 'tank', count: 3 }, { type: 'disruptor', count: 3 }, { type: 'emp_drone', count: 3 }, { type: 'runner', count: 8 }], spawnDelay: 350, spawnPoints: 2 },
        // Wave 15: Tunnelers arrive (burrow under walls)
        { number: 15, enemies: [{ type: 'tunneler', count: 4 }, { type: 'tank', count: 4 }, { type: 'wall_breaker', count: 4 }, { type: 'leech', count: 4 }, { type: 'bomber', count: 5 }, { type: 'home_wrecker', count: 3 }, { type: 'river_serpent', count: 4 }], spawnDelay: 340, spawnPoints: 2 },
        // Wave 16: Swarms unleashed
        { number: 16, enemies: [{ type: 'swarm', count: 25 }, { type: 'disruptor', count: 3 }, { type: 'drill_worm', count: 3 }, { type: 'emp_drone', count: 4 }], spawnDelay: 300, spawnPoints: 2 },
        // Wave 17
        { number: 17, enemies: [{ type: 'tank', count: 4 }, { type: 'swarm', count: 20 }, { type: 'bomber', count: 5 }, { type: 'leech', count: 3 }, { type: 'river_serpent', count: 4 }, { type: 'zapper', count: 4 }], spawnDelay: 300, spawnPoints: 3 },
        // Wave 18: Nullifiers arrive (target shields)
        { number: 18, enemies: [{ type: 'nullifier', count: 3 }, { type: 'shielded_grunt', count: 10 }, { type: 'swarm', count: 20 }, { type: 'disruptor', count: 3 }, { type: 'home_wrecker', count: 3 }, { type: 'zapper', count: 5 }], spawnDelay: 280, spawnPoints: 3 },
        // Wave 19: Heavy Flyers arrive + pre-boss buildup
        { number: 19, enemies: [{ type: 'heavy_flyer', count: 3 }, { type: 'tank', count: 5 }, { type: 'nullifier', count: 3 }, { type: 'bomber', count: 6 }, { type: 'leech', count: 4 }, { type: 'swarm', count: 20 }, { type: 'emp_drone', count: 4 }, { type: 'zapper', count: 6 }], spawnDelay: 260, spawnPoints: 3 },
        // Wave 20: BOSS WAVE — Overload Boss
        { number: 20, enemies: [{ type: 'overload_boss', count: 1 }, { type: 'heavy_tank', count: 2 }, { type: 'shielded_grunt', count: 10 }, { type: 'swarm', count: 18 }, { type: 'nullifier', count: 3 }], spawnDelay: 250, spawnPoints: 3 },
        // Wave 21-50: Increasingly diverse and difficult
        { number: 21, enemies: [{ type: 'heavy_tank', count: 1 }, { type: 'bomber', count: 5 }, { type: 'emp_drone', count: 4 }, { type: 'disruptor', count: 3 }, { type: 'runner', count: 8 }, { type: 'plasma_parasite', count: 4 }, { type: 'zapper', count: 5 }], spawnDelay: 250, spawnPoints: 3 },
        { number: 22, enemies: [{ type: 'heavy_tank', count: 2 }, { type: 'wall_breaker', count: 10 }, { type: 'nullifier', count: 4 }, { type: 'scout_drone', count: 6 }, { type: 'tunneler', count: 3 }, { type: 'drill_worm', count: 3 }, { type: 'swarm', count: 20 }, { type: 'river_serpent', count: 3 }], spawnDelay: 240, spawnPoints: 3 },
        { number: 23, enemies: [{ type: 'heavy_tank', count: 2 }, { type: 'nullifier', count: 3 }, { type: 'bomber', count: 5 }, { type: 'home_wrecker', count: 3 }, { type: 'leech', count: 3 }, { type: 'plasma_parasite', count: 5 }, { type: 'zapper', count: 6 }], spawnDelay: 230, spawnPoints: 3 },
        { number: 24, enemies: [{ type: 'tank', count: 5 }, { type: 'swarm', count: 85 }, { type: 'disruptor', count: 3 }, { type: 'emp_drone', count: 4 }], spawnDelay: 220, spawnPoints: 3 },
        { number: 25, enemies: [{ type: 'saboteur', count: 3 }, { type: 'heavy_tank', count: 2 }, { type: 'nullifier', count: 2 }, { type: 'drill_worm', count: 3 }, { type: 'swarm', count: 15 }, { type: 'plasma_parasite', count: 6 }, { type: 'zapper', count: 8 }], spawnDelay: 210, spawnPoints: 3 },
        { number: 26, enemies: [{ type: 'saboteur', count: 4 }, { type: 'heavy_flyer', count: 5 }, { type: 'tunneler', count: 5 }, { type: 'phase_walker', count: 3 }, { type: 'bomber', count: 6 }, { type: 'home_wrecker', count: 3 }, { type: 'leech', count: 3 }, { type: 'river_serpent', count: 4 }], spawnDelay: 200, spawnPoints: 3 },
        { number: 27, enemies: [{ type: 'heavy_tank', count: 3 }, { type: 'heavy_flyer', count: 2 }, { type: 'saboteur', count: 3 }, { type: 'swarm', count: 25 }, { type: 'disruptor', count: 3 }, { type: 'nullifier', count: 2 }, { type: 'emp_sniper', count: 3 }, { type: 'zapper', count: 6 }], spawnDelay: 200, spawnPoints: 3 },
        { number: 28, enemies: [{ type: 'tank', count: 5 }, { type: 'bomber', count: 6 }, { type: 'tunneler', count: 5 }, { type: 'disruptor', count: 5 }, { type: 'drill_worm', count: 3 }, { type: 'emp_drone', count: 5 }, { type: 'leech', count: 3 }], spawnDelay: 190, spawnPoints: 3 },
        { number: 29, enemies: [{ type: 'heavy_tank', count: 3 }, { type: 'home_wrecker', count: 4 }, { type: 'swarm', count: 30 }, { type: 'nullifier', count: 3 }, { type: 'saboteur', count: 3 }, { type: 'emp_sniper', count: 3 }, { type: 'plasma_parasite', count: 5 }], spawnDelay: 180, spawnPoints: 3 },
        { number: 30, enemies: [{ type: 'overload_boss', count: 2 }, { type: 'siege_engine', count: 1 }, { type: 'heavy_tank', count: 2 }, { type: 'bomber', count: 5 }, { type: 'disruptor', count: 3 }, { type: 'swarm', count: 20 }, { type: 'river_serpent', count: 4 }, { type: 'tunneler', count: 8 }, { type: 'emp_drone', count: 10 }, { type: 'wall_breaker', count: 5 }], spawnDelay: 170, spawnPoints: 4 },
        { number: 31, enemies: [{ type: 'siege_engine', count: 1 }, { type: 'saboteur', count: 5 }, { type: 'nullifier', count: 3 }, { type: 'home_wrecker', count: 3 }, { type: 'emp_drone', count: 5 }, { type: 'zapper', count: 8 }, { type: 'emp_sniper', count: 3 }], spawnDelay: 170, spawnPoints: 4 },
        { number: 32, enemies: [{ type: 'heavy_tank', count: 4 }, { type: 'siege_engine', count: 1 }, { type: 'drill_worm', count: 4 }, { type: 'leech', count: 4 }, { type: 'swarm', count: 25 }, { type: 'bomber', count: 7 }, { type: 'runner', count: 15 }, { type: 'nullifier', count: 5 }], spawnDelay: 160, spawnPoints: 4 },
        { number: 33, enemies: [{ type: 'siege_engine', count: 2 }, { type: 'disruptor', count: 4 }, { type: 'nullifier', count: 3 }, { type: 'bomber', count: 6 }, { type: 'river_serpent', count: 5 }, { type: 'plasma_parasite', count: 6 }, { type: 'zapper', count: 8 }], spawnDelay: 160, spawnPoints: 4 },
        { number: 34, enemies: [{ type: 'heavy_tank', count: 4 }, { type: 'heavy_flyer', count: 3 }, { type: 'tunneler', count: 4 }, { type: 'swarm', count: 35 }, { type: 'home_wrecker', count: 4 }, { type: 'saboteur', count: 4 }, { type: 'leech', count: 3 }, { type: 'emp_drone', count: 10 }, { type: 'disruptor', count: 6 }, { type: 'wall_breaker', count: 5 }], spawnDelay: 150, spawnPoints: 4 },
        { number: 35, enemies: [{ type: 'siege_engine', count: 2 }, { type: 'heavy_tank', count: 3 }, { type: 'drill_worm', count: 4 }, { type: 'disruptor', count: 4 }, { type: 'emp_drone', count: 6 }, { type: 'nullifier', count: 3 }, { type: 'emp_sniper', count: 4 }, { type: 'zapper', count: 10 }], spawnDelay: 150, spawnPoints: 4 },
        { number: 36, enemies: [{ type: 'heavy_tank', count: 5 }, { type: 'bomber', count: 8 }, { type: 'home_wrecker', count: 4 }, { type: 'leech', count: 4 }, { type: 'river_serpent', count: 5 }, { type: 'swarm', count: 20 }, { type: 'tunneler', count: 6 }, { type: 'nullifier', count: 5 }], spawnDelay: 140, spawnPoints: 4 },
        { number: 37, enemies: [{ type: 'siege_engine', count: 2 }, { type: 'tank', count: 6 }, { type: 'swarm', count: 30 }, { type: 'disruptor', count: 4 }, { type: 'nullifier', count: 3 }, { type: 'plasma_parasite', count: 8 }, { type: 'emp_sniper', count: 4 }], spawnDelay: 140, spawnPoints: 4 },
        { number: 38, enemies: [{ type: 'siege_engine', count: 3 }, { type: 'heavy_tank', count: 4 }, { type: 'drill_worm', count: 4 }, { type: 'saboteur', count: 5 }, { type: 'leech', count: 4 }, { type: 'swarm', count: 15 }, { type: 'bomber', count: 7 }, { type: 'emp_drone', count: 8 }], spawnDelay: 130, spawnPoints: 4 },
        { number: 39, enemies: [{ type: 'heavy_tank', count: 5 }, { type: 'nullifier', count: 4 }, { type: 'swarm', count: 35 }, { type: 'home_wrecker', count: 4 }, { type: 'emp_drone', count: 6 }, { type: 'zapper', count: 12 }, { type: 'plasma_parasite', count: 6 }], spawnDelay: 130, spawnPoints: 4 },
        // Wave 40: Phase Walkers + Procedural Boss
        { number: 40, enemies: [{ type: 'overload_boss', count: 3 }, { type: 'phase_walker', count: 3 }, { type: 'siege_engine', count: 2 }, { type: 'heavy_tank', count: 3 }, { type: 'disruptor', count: 4 }, { type: 'swarm', count: 25 }, { type: 'river_serpent', count: 5 }, { type: 'tunneler', count: 6 }, { type: 'wall_breaker', count: 5 }, { type: 'leech', count: 12 }], spawnDelay: 120, spawnPoints: 4 },
        { number: 41, enemies: [{ type: 'phase_walker', count: 4 }, { type: 'saboteur', count: 5 }, { type: 'nullifier', count: 3 }, { type: 'heavy_tank', count: 3 }, { type: 'leech', count: 4 }, { type: 'emp_sniper', count: 5 }, { type: 'zapper', count: 10 }], spawnDelay: 120, spawnPoints: 4 },
        { number: 42, enemies: [{ type: 'siege_engine', count: 3 }, { type: 'phase_walker', count: 3 }, { type: 'swarm', count: 40 }, { type: 'drill_worm', count: 4 }, { type: 'home_wrecker', count: 4 }, { type: 'bomber', count: 8 }, { type: 'nullifier', count: 5 }, { type: 'heavy_tank', count: 4 }], spawnDelay: 110, spawnPoints: 4 },
        { number: 43, enemies: [{ type: 'heavy_tank', count: 6 }, { type: 'phase_walker', count: 4 }, { type: 'disruptor', count: 5 }, { type: 'nullifier', count: 4 }, { type: 'emp_drone', count: 6 }, { type: 'plasma_parasite', count: 8 }], spawnDelay: 110, spawnPoints: 4 },
        { number: 44, enemies: [{ type: 'siege_engine', count: 3 }, { type: 'heavy_tank', count: 5 }, { type: 'phase_walker', count: 4 }, { type: 'bomber', count: 8 }, { type: 'leech', count: 4 }, { type: 'swarm', count: 20 }, { type: 'tunneler', count: 6 }, { type: 'emp_drone', count: 10 }, { type: 'wall_breaker', count: 10 }], spawnDelay: 100, spawnPoints: 4 },
        { number: 45, enemies: [{ type: 'siege_engine', count: 4 }, { type: 'phase_walker', count: 5 }, { type: 'drill_worm', count: 5 }, { type: 'home_wrecker', count: 5 }, { type: 'saboteur', count: 5 }, { type: 'river_serpent', count: 6 }, { type: 'emp_sniper', count: 5 }, { type: 'zapper', count: 12 }], spawnDelay: 100, spawnPoints: 4 },
        { number: 46, enemies: [{ type: 'heavy_tank', count: 6 }, { type: 'siege_engine', count: 3 }, { type: 'nullifier', count: 5 }, { type: 'disruptor', count: 5 }, { type: 'swarm', count: 40 }, { type: 'phase_walker', count: 4 }, { type: 'bomber', count: 8 }, { type: 'home_wrecker', count: 6 }], spawnDelay: 90, spawnPoints: 4 },
        { number: 47, enemies: [{ type: 'siege_engine', count: 4 }, { type: 'heavy_tank', count: 5 }, { type: 'phase_walker', count: 5 }, { type: 'leech', count: 5 }, { type: 'emp_drone', count: 8 }, { type: 'plasma_parasite', count: 8 }, { type: 'emp_sniper', count: 5 }], spawnDelay: 90, spawnPoints: 4 },
        { number: 48, enemies: [{ type: 'siege_engine', count: 5 }, { type: 'phase_walker', count: 6 }, { type: 'bomber', count: 10 }, { type: 'home_wrecker', count: 5 }, { type: 'drill_worm', count: 5 }, { type: 'swarm', count: 25 }, { type: 'heavy_tank', count: 4 }, { type: 'tunneler', count: 6 }], spawnDelay: 80, spawnPoints: 4 },
        { number: 49, enemies: [{ type: 'heavy_tank', count: 8 }, { type: 'siege_engine', count: 4 }, { type: 'nullifier', count: 5 }, { type: 'disruptor', count: 5 }, { type: 'saboteur', count: 6 }, { type: 'zapper', count: 15 }, { type: 'emp_sniper', count: 5 }, { type: 'plasma_parasite', count: 8 }, { type: 'wall_breaker', count: 15 }], spawnDelay: 70, spawnPoints: 4 },
        // Wave 50: Everything at max
        { number: 50, enemies: [{ type: 'overload_boss', count: 5 }, { type: 'siege_engine', count: 6 }, { type: 'heavy_tank', count: 6 }, { type: 'phase_walker', count: 8 }, { type: 'bomber', count: 10 }, { type: 'swarm', count: 50 }, { type: 'nullifier', count: 5 }, { type: 'disruptor', count: 5 }, { type: 'home_wrecker', count: 5 }, { type: 'drill_worm', count: 5 }, { type: 'leech', count: 5 }, { type: 'river_serpent', count: 6 }, { type: 'runner', count: 15 }, { type: 'tunneler', count: 8 }, { type: 'heavy_flyer', count: 4 }, { type: 'zapper', count: 15 }, { type: 'plasma_parasite', count: 10 }, { type: 'emp_sniper', count: 6 }], spawnDelay: 60, spawnPoints: 4 }
    ],

    // ------------------------------------------------------------------------
    // Difficulty Presets
    // ------------------------------------------------------------------------
    DIFFICULTY: {
        watt: {
            name: 'Watt',
            icon: '⚡',
            subtitle: 'Easy',
            enemyHPMult: 0.7,
            enemyDamageMult: 0.7,
            enemySpeedMult: 0.9,
            buildingCostMult: 0.8,
            buildingEnergyMult: 0.8,
            waveInterval: 135,
            firstWaveDelay: 210,
            killRewardMult: 1.2,
            waveBonusMult: 1.3,
            startMoney: 2500,
            pollutionDecayMult: 1.3,
            workerRecruitMult: 1.3,
            scalingPerWave: 0.05,
            maxWaves: 20,
            scoreMult: 0.8
        },
        volt: {
            name: 'Volt',
            icon: '🔌',
            subtitle: 'Normal',
            enemyHPMult: 1.0,
            enemyDamageMult: 1.0,
            enemySpeedMult: 1.0,
            buildingCostMult: 1.0,
            buildingEnergyMult: 1.0,
            waveInterval: 120,
            firstWaveDelay: 180,
            killRewardMult: 1.0,
            waveBonusMult: 1.0,
            startMoney: 2000,
            pollutionDecayMult: 1.0,
            workerRecruitMult: 1.0,
            scalingPerWave: 0.08,
            maxWaves: 30,
            scoreMult: 1.0
        },
        amp: {
            name: 'Amp',
            icon: '🔥',
            subtitle: 'Hard',
            enemyHPMult: 1.4,
            enemyDamageMult: 1.3,
            enemySpeedMult: 1.1,
            buildingCostMult: 1.3,
            buildingEnergyMult: 1.2,
            waveInterval: 105,
            firstWaveDelay: 150,
            killRewardMult: 0.9,
            waveBonusMult: 0.8,
            startMoney: 1500,
            pollutionDecayMult: 0.8,
            workerRecruitMult: 0.8,
            scalingPerWave: 0.12,
            maxWaves: 40,
            scoreMult: 1.2
        },
        lightning: {
            name: 'Lightning',
            icon: '⛈️',
            subtitle: 'Extreme',
            enemyHPMult: 2.0,
            enemyDamageMult: 1.8,
            enemySpeedMult: 1.2,
            buildingCostMult: 1.6,
            buildingEnergyMult: 1.5,
            waveInterval: 90,
            firstWaveDelay: 120,
            killRewardMult: 0.8,
            waveBonusMult: 0.6,
            startMoney: 1400,
            pollutionDecayMult: 0.6,
            workerRecruitMult: 0.6,
            scalingPerWave: 0.15,
            maxWaves: 50,
            scoreMult: 1.5
        }
    },

    // ------------------------------------------------------------------------
    // Category Display Order & Icons
    // ------------------------------------------------------------------------
    CATEGORY_ORDER: ['power', 'storage', 'mining', 'weapons', 'defense', 'housing', 'environment', 'grid', 'consumer'],

    CATEGORY_ICONS: {
        power: '⚡',
        storage: '🔋',
        mining: '⛏️',
        weapons: '🎯',
        defense: '🛡️',
        housing: '🏠',
        environment: '🌿',
        grid: '📡',
        consumer: '💲'
    },

    // ------------------------------------------------------------------------
    // Energy Distribution Priority (lower number = higher priority)
    // ------------------------------------------------------------------------
    ENERGY_PRIORITY: {
        shields_active: 1,
        weapons: 2,
        miners: 3,
        housing: 4,
        carbon_collectors: 5,
        batteries: 6,
        consumer_batteries: 7
    },

    // ------------------------------------------------------------------------
    // Helper Functions
    // ------------------------------------------------------------------------

    /**
     * Returns an array of [key, definition] pairs for every building in the
     * given category.
     */
    getBuildingsInCategory: function (category) {
        var results = [];
        var keys = Object.keys(this.BUILDINGS);
        for (var i = 0; i < keys.length; i++) {
            var key = keys[i];
            if (this.BUILDINGS[key].category === category) {
                results.push([key, this.BUILDINGS[key]]);
            }
        }
        return results;
    }
};
