var Tutorial = (function() {
    var _steps = [];
    var _currentStep = 0;
    var _active = false;
    var _boxEl = null;
    var _flashedEls = [];
    var _initialCounts = {};
    var _stepComplete = false;
    var _settingsKey = 'voltdefense_settings';

    // ── Settings persistence ──

    function _loadSettings() {
        try {
            var raw = localStorage.getItem(_settingsKey);
            if (raw) return JSON.parse(raw);
        } catch (e) {}
        return { tutorialEnabled: true };
    }

    function _saveSettings(settings) {
        try {
            localStorage.setItem(_settingsKey, JSON.stringify(settings));
        } catch (e) {}
    }

    // ── Building helpers ──

    function _countBuildingsByType(type) {
        if (typeof Buildings === 'undefined' || !Buildings.getAll) return 0;
        var all = Buildings.getAll();
        var count = 0;
        for (var i = 0; i < all.length; i++) {
            if (all[i].type === type && all[i].hp > 0) count++;
        }
        return count;
    }

    function _countBuildingsByCategory(category) {
        if (typeof Buildings === 'undefined' || !Buildings.getAll) return 0;
        if (typeof Config === 'undefined' || !Config.BUILDINGS) return 0;
        var all = Buildings.getAll();
        var count = 0;
        for (var i = 0; i < all.length; i++) {
            var def = Config.BUILDINGS[all[i].type];
            if (def && def.category === category && all[i].hp > 0) count++;
        }
        return count;
    }

    // ── Flash helpers ──

    function _flashElement(selector) {
        _clearFlash();
        var el = document.querySelector(selector);
        if (el) { el.classList.add('tutorial-flash'); _flashedEls.push(el); }
    }

    function _flashMultiple(selectors) {
        _clearFlash();
        for (var i = 0; i < selectors.length; i++) {
            var el = document.querySelector(selectors[i]);
            if (el) { el.classList.add('tutorial-flash'); _flashedEls.push(el); }
        }
    }

    function _clearFlash() {
        for (var i = 0; i < _flashedEls.length; i++) {
            _flashedEls[i].classList.remove('tutorial-flash');
        }
        _flashedEls = [];
    }

    // ── Step definitions ──

    function _defineSteps() {
        _steps = [
            // Step 0: Welcome
            {
                title: 'Welcome to Volt Defense! ⚡',
                text: 'Volt Defense is a tower defense game where you build and manage a power grid to fuel your weapons and defenses.<br><br>Energy flows through cables connecting your buildings — without power, nothing works. You\'ll place power plants to generate energy, batteries to store it, and weapons to destroy waves of enemies marching toward your core.<br><br>Your goal: keep your core alive as long as possible against increasingly dangerous waves.<br><br>Let\'s walk through the basics!',
                type: 'info'
            },
            // Step 1: Build a Battery
            {
                title: 'Step 1: Build a Battery 🔋',
                text: 'Batteries store energy generated by your power plants. Without storage, excess energy is wasted and your weapons won\'t have reserves during high-demand moments.<br><br>Click the <b>Storage</b> category below, then select <b>Small Battery</b> and place it near your starting buildings.<br><br>Capacitors are similar but hold much less energy (about 1/10th) — however they charge and discharge 10x faster, making them perfect for powering weapons that need quick bursts of energy.',
                type: 'interactive',
                flash: '[data-action="select-category"][data-category="storage"]',
                onEnter: function() {
                    _initialCounts.storage = _countBuildingsByCategory('storage');
                },
                check: function() {
                    return _countBuildingsByCategory('storage') > _initialCounts.storage;
                }
            },
            // Step 2: Build a Pylon
            {
                title: 'Step 2: Build a Pylon 🔌',
                text: 'Pylons extend your power grid\'s reach. Buildings must be within 200 pixels of another building or pylon to be placed — pylons act as relay points, letting you spread your grid across the map.<br><br>Connect buildings with cables to allow energy to flow between them. Regular <b>Pylons</b> support up to <b>4 cable connections</b>. <b>HC (High Capacity) Pylons</b> support up to <b>6 connections</b> and can transfer more energy through their cables.<br><br>Open the <b>Grid</b> category and <b>build a Pylon</b>!',
                type: 'interactive',
                flash: '[data-action="select-category"][data-category="grid"]',
                onEnter: function() {
                    _initialCounts.pylon = _countBuildingsByType('pylon');
                    _initialCounts.hc_pylon = _countBuildingsByType('hc_pylon');
                },
                check: function() {
                    return _countBuildingsByType('pylon') > _initialCounts.pylon ||
                           _countBuildingsByType('hc_pylon') > _initialCounts.hc_pylon;
                }
            },
            // Step 3: Build a Solar Panel
            {
                title: 'Step 3: Build a Power Plant ⚡',
                text: 'Power plants generate the energy your grid needs. Here\'s a quick overview:<br><br>' +
                    '☀️ <b>Solar Panel</b> — Free, clean energy during daytime. No pollution, no fuel, but produces nothing at night.<br>' +
                    '🌬️ <b>Wind Turbine</b> — Free energy scaled by wind speed. Clean but inconsistent.<br>' +
                    '🪨 <b>Coal Plant</b> — Reliable power using coal. Produces pollution.<br>' +
                    '🛢️ <b>Gas Plant</b> — Burns oil for steady power. Moderate pollution.<br>' +
                    '☢️ <b>Nuclear Plant</b> — Massive energy output using uranium. Low pollution but expensive.<br>' +
                    '💧 <b>Hydro Plant</b> — Must be built on rivers. Clean energy based on current speed.<br><br>' +
                    'Open the <b>Power</b> category and <b>build a Solar Panel</b> — it\'s free to run!',
                type: 'interactive',
                flash: '[data-action="select-category"][data-category="power"]',
                onEnter: function() {
                    _initialCounts.solar = _countBuildingsByType('solar');
                },
                check: function() {
                    return _countBuildingsByType('solar') > _initialCounts.solar;
                }
            },
            // Step 4: Pollution Info
            {
                title: 'Pollution 💨',
                text: 'Fossil fuel power plants (Coal, Gas) generate pollution every time they produce energy. Pollution has serious gameplay effects:<br><br>' +
                    '• <b>Clean (0-49):</b> No effects<br>' +
                    '• <b>Low (50-149):</b> Enemies move 5% faster<br>' +
                    '• <b>Moderate (150-299):</b> 50% harder to recruit workers, enemies move 10% faster<br>' +
                    '• <b>High (300-499):</b> No new workers, existing workers leave, enemies 20% faster<br>' +
                    '• <b>Critical (500+):</b> Workers leave faster, enemies faster, -20% energy output<br><br>' +
                    'Pollution decays slowly over time. You can build <b>Carbon Collectors</b> (in the Environment category) which use energy to actively reduce pollution. Plan your power mix carefully!',
                type: 'info'
            },
            // Step 5: Build a House
            {
                title: 'Step 5: Build a House 🏠',
                text: 'Every building requires workers to operate. No workers means the building stays inactive — it won\'t generate power, fire weapons, or do anything useful.<br><br>Houses provide worker capacity. Bigger houses hold more workers and are more efficient per worker, but use more electricity. You start with one house and one wind turbine.<br><br>If you run out of worker capacity, you won\'t be able to build new structures. Keep an eye on the 👷 worker count in the top HUD bar.<br><br>Build a house from the <b>Housing</b> category!',
                type: 'interactive',
                flash: '[data-action="select-category"][data-category="housing"]',
                onEnter: function() {
                    _initialCounts.housing = _countBuildingsByCategory('housing');
                },
                check: function() {
                    return _countBuildingsByCategory('housing') > _initialCounts.housing;
                }
            },
            // Step 6: Consumer Battery
            {
                title: 'Step 6: Consumer Economy 💲',
                text: 'Need more money? The <b>Consumer</b> category is your income engine!<br><br><b>Consumer Batteries</b> fill up with energy from your grid. Once full, they are automatically sold for cash and replaced with an empty one. This is your main way to earn money beyond enemy kill rewards.<br><br><b>Consumer Grid Connects</b> sell energy directly from your grid in real time — no storage needed, but they require a steady power supply.<br><br><b>Consumer Markets</b> sell raw materials like iron, coal, and uranium for cash.<br><br>Open the <b>Consumer</b> category and <b>build a Consumer Battery</b>!',
                type: 'interactive',
                flash: '[data-action="select-category"][data-category="consumer"]',
                onEnter: function() {
                    _initialCounts.consumer_battery = _countBuildingsByType('consumer_battery');
                },
                check: function() {
                    return _countBuildingsByType('consumer_battery') > _initialCounts.consumer_battery;
                }
            },
            // Step 7: Build a Blaster
            {
                title: 'Step 7: Build a Weapon 🔫',
                text: 'Enemies are coming! You need weapons to defend your core.<br><br>Let\'s start with a <b>Blaster</b> — it\'s cheap and effective against early enemies. Open the <b>Weapons</b> category and place a <b>Blaster T1</b>.<br><br>Remember: weapons need energy to fire, so make sure they\'re connected to your grid!<br><br>💡 <b>Tip:</b> You can <b>right-click</b> to cancel building placement at any time. You can also <b>left-click on an existing building</b> while placing to inspect its details.',
                type: 'interactive',
                flash: '[data-action="select-category"][data-category="weapons"]',
                onEnter: function() {
                    _initialCounts.blaster_t1 = _countBuildingsByType('blaster_t1');
                },
                check: function() {
                    return _countBuildingsByType('blaster_t1') > _initialCounts.blaster_t1;
                }
            },
            // Step 8: Weapons Overview
            {
                title: 'Weapons Overview ⚔️',
                text: 'Here are all the weapons available to you:<br><br>' +
                    '🔫 <b>Blaster</b> — Fast-firing energy bolts. Cheap, reliable, great all-around.<br>' +
                    '🔴 <b>Laser</b> — Continuous beam that doubles damage every second on the same target. High energy cost.<br>' +
                    '🚀 <b>Missile</b> — Fires at the furthest enemy. Uses iron ammo. Moderate damage.<br>' +
                    '⚡ <b>Tesla Coil</b> — Chain lightning that hits multiple enemies. Area denial.<br>' +
                    '🔥 <b>Flamethrower</b> — Short range cone of fire. Devastating to groups.<br>' +
                    '🎯 <b>Railgun</b> — Extreme range, high single-target damage. Slow reload.<br>' +
                    '💫 <b>EMP Tower</b> — Stuns enemies in range. No damage but invaluable support.<br>' +
                    '💣 <b>Mortar</b> — Lobs explosive shells with splash damage. Can\'t hit close targets.<br>' +
                    '🤖 <b>Drone Bay</b> — Deploys autonomous attack drones.<br>' +
                    '💥 <b>Mine Layer</b> — Places proximity mines that explode when enemies get close.<br>' +
                    '🔩 <b>Autocannon</b> — Rapid-fire physical rounds. Bypasses some armor.<br>' +
                    '🔮 <b>Plasma Cannon</b> — Ignores all armor. Uses uranium.<br>' +
                    '☄️ <b>Fusion Beam</b> — Ultimate weapon. Massive damage and range.<br><br>' +
                    '⬆️ <b>Upgrades:</b> Many buildings can be upgraded in-place! <b>Blasters</b>, <b>Lasers</b>, <b>Missiles</b>, and <b>Shields</b> can be upgraded through 2-3 tiers. <b>Miners</b>, <b>Batteries</b>, <b>Capacitors</b>, <b>Houses</b>, <b>Carbon Collectors</b>, <b>Pylons</b>, and even the <b>Core</b> can also be upgraded. Click a building to see if an upgrade is available.',
                type: 'info'
            },
            // Step 9: Cables & Connections
            {
                title: 'Cables & Connections 🔌',
                text: 'Energy flows through <b>cables</b> connecting your buildings. Most buildings <b>auto-connect</b> to the nearest building when placed.<br><br>However, you may need to <b>manually connect</b> cables sometimes — especially to control which buildings power which. To manually connect: <b>right-click</b> on building A, then <b>right-click</b> on building B.<br><br>⚠️ <b>Connection order matters!</b> Energy flows from the first building to the second. Connect generators → storage → consumers in that order for best results.<br><br>Each building supports up to <b>4 cable connections</b> (HC Pylons support 6). You can press <b>E</b> to toggle the energy flow overlay and see how power moves through your grid.',
                type: 'info'
            },
            // Step 10: Resources & Mining
            {
                title: 'Resources & Mining ⛏️',
                text: 'Your map contains resource deposits: <b>Iron</b> (common), <b>Coal</b> (common), <b>Oil</b> (moderate), and <b>Uranium</b> (rare).<br><br>Build <b>Miners</b> on top of deposits to extract resources — miners need energy and workers to operate.<br><br>Iron is used for missiles and advanced buildings. Coal fuels Coal Plants. Uranium powers Nuclear Plants and Plasma Cannons. Oil runs Gas Plants and Flamethrowers.<br><br>You\'ll also want a <b>Smelter</b> — it converts iron into steel, which is needed for advanced weapons like Autocannons and Mine Layers.<br><br>Plan your resource extraction early!',
                type: 'info'
            },
            // Step 11: Walls & Shields
            {
                title: 'Walls & Shields 🛡️',
                text: '<b>Walls</b> are cheap barriers that block enemy movement, forcing them to path around or destroy them. Use walls to create mazes and chokepoints that keep enemies in your weapons\' firing lanes longer.<br><br><b>Electric Walls</b> deal contact damage to enemies touching them but cost energy.<br><br><b>Shield Generators</b> create a 400-pixel diameter energy bubble that enemies must destroy before passing through. Shields use a lot of energy constantly, and taking hits drains even more.<br><br>Place shields at key chokepoints and make sure they have dedicated power. Combine walls, shields, and weapons for layered defense!',
                type: 'info'
            },
            // Step 12: Final
            {
                title: 'You\'re Ready! 🎉',
                text: 'You now know the basics of Volt Defense!<br><br><b>Quick reference:</b><br>' +
                    '• <b>Left-click</b> a building to see its details, stats, and upgrade options<br>' +
                    '• <b>Right-click</b> to cancel placement or manually connect cables<br>' +
                    '• <b>E</b> key toggles the energy flow overlay<br>' +
                    '• <b>WASD</b> or drag to pan the map<br><br>' +
                    'Check out the 📖 <b>Enemy Glossary</b> and ⚔️ <b>Weapons Glossary</b> buttons in the HUD bar for detailed stats.<br><br>Click <b>Complete</b> to receive a bonus <b>$500</b> — good luck defending your core, Commander! ⚡',
                type: 'info',
                onEnter: function() {
                    _flashMultiple(['[data-action="enemy-glossary"]', '[data-action="weapons-glossary"]']);
                }
            }
        ];
    }

    // ── UI creation ──

    function _createBox() {
        if (_boxEl) return;

        _boxEl = document.createElement('div');
        _boxEl.id = 'tutorial-box';
        _boxEl.style.cssText = 'position:fixed;left:20px;top:80px;width:380px;z-index:9999;' +
            'background:rgba(10,14,23,0.95);border:2px solid rgba(100,180,255,0.4);' +
            'border-radius:12px;color:#e0e8f0;font-family:Arial,Helvetica,sans-serif;' +
            'font-size:14px;box-shadow:0 4px 24px rgba(0,0,0,0.6);user-select:none;';

        _boxEl.innerHTML = _buildHTML();
        document.body.appendChild(_boxEl);

        // Make draggable
        _makeDraggable();

        // Bind events
        var closeBtn = _boxEl.querySelector('#tut-close-btn');
        if (closeBtn) closeBtn.addEventListener('click', _onCloseClick);

        var nextBtn = _boxEl.querySelector('#tut-next-btn');
        if (nextBtn) nextBtn.addEventListener('click', _onNextClick);
    }

    function _buildHTML() {
        var step = _steps[_currentStep];
        var isLast = _currentStep === _steps.length - 1;
        var btnText = isLast ? 'Complete! 🎉' : 'Next ▶';
        var isInteractive = step.type === 'interactive';
        var btnDisabled = isInteractive && !_stepComplete;

        return '' +
            // Title bar
            '<div style="display:flex;align-items:center;justify-content:space-between;' +
            'padding:10px 14px;background:rgba(40,60,90,0.6);border-radius:10px 10px 0 0;' +
            'border-bottom:1px solid rgba(100,180,255,0.2);cursor:move;" id="tut-titlebar">' +
                '<span style="font-weight:bold;font-size:15px;color:#7fd4ff;">' + step.title + '</span>' +
                '<button id="tut-close-btn" style="background:none;border:none;color:#ff6b6b;' +
                'font-size:20px;cursor:pointer;padding:0 4px;line-height:1;" title="Close tutorial">✕</button>' +
            '</div>' +
            // Body
            '<div style="padding:14px 16px;line-height:1.5;max-height:480px;overflow-y:auto;" id="tut-body">' +
                step.text +
                (isInteractive && _stepComplete ? '<div style="margin-top:10px;color:#4cff8e;font-weight:bold;">✅ Done! Click Next to continue.</div>' : '') +
            '</div>' +
            // Footer
            '<div style="display:flex;align-items:center;justify-content:space-between;' +
            'padding:10px 14px;border-top:1px solid rgba(100,180,255,0.15);">' +
                '<span style="font-size:12px;color:#8899aa;">Step ' + (_currentStep + 1) + ' of ' + _steps.length + '</span>' +
                '<button id="tut-next-btn" style="padding:8px 20px;border:none;border-radius:6px;' +
                'font-size:14px;font-weight:bold;cursor:' + (btnDisabled ? 'not-allowed' : 'pointer') + ';' +
                'background:' + (btnDisabled ? 'rgba(60,70,90,0.8)' : 'linear-gradient(135deg,#2a8af6,#7c3aed)') + ';' +
                'color:' + (btnDisabled ? '#667' : '#fff') + ';transition:all 0.2s;"' +
                (btnDisabled ? ' disabled' : '') + '>' + btnText + '</button>' +
            '</div>';
    }

    function _refreshBox() {
        if (!_boxEl) return;
        // Preserve position
        var left = _boxEl.style.left;
        var top = _boxEl.style.top;
        _boxEl.innerHTML = _buildHTML();
        _boxEl.style.left = left;
        _boxEl.style.top = top;

        var closeBtn = _boxEl.querySelector('#tut-close-btn');
        if (closeBtn) closeBtn.addEventListener('click', _onCloseClick);

        var nextBtn = _boxEl.querySelector('#tut-next-btn');
        if (nextBtn) nextBtn.addEventListener('click', _onNextClick);

        _makeDraggable();
    }

    // ── Draggable ──

    function _makeDraggable() {
        var titlebar = _boxEl.querySelector('#tut-titlebar');
        if (!titlebar) return;

        var dragging = false;
        var offsetX = 0;
        var offsetY = 0;

        titlebar.addEventListener('mousedown', function(e) {
            if (e.target.id === 'tut-close-btn') return;
            dragging = true;
            offsetX = e.clientX - _boxEl.offsetLeft;
            offsetY = e.clientY - _boxEl.offsetTop;
            e.preventDefault();
        });

        document.addEventListener('mousemove', function(e) {
            if (!dragging) return;
            _boxEl.style.left = (e.clientX - offsetX) + 'px';
            _boxEl.style.top = (e.clientY - offsetY) + 'px';
        });

        document.addEventListener('mouseup', function() {
            dragging = false;
        });
    }

    // ── Event handlers ──

    function _onCloseClick() {
        if (typeof UI !== 'undefined' && UI.showModal) {
            UI.showModal(
                '⚠️ Skip Tutorial?',
                'Are you sure you want to skip the tutorial?<br>You can re-enable it from the main menu.',
                [
                    { label: 'Skip Tutorial', action: 'skip-tutorial' },
                    { label: 'Cancel', action: 'close-modal' }
                ]
            );
        } else {
            Tutorial.close();
        }
    }

    function _onNextClick() {
        var step = _steps[_currentStep];
        if (step.type === 'interactive' && !_stepComplete) return;

        if (_currentStep >= _steps.length - 1) {
            // Completed the tutorial — award bonus
            if (typeof Economy !== 'undefined' && Economy.addMoney) {
                Economy.addMoney(500);
            }
            if (typeof UI !== 'undefined' && UI.showToast) {
                UI.showToast('🎉 Tutorial complete! +$500 bonus!', 'success', 3000);
            }
            Tutorial.close();
            return;
        }

        _currentStep++;
        _stepComplete = false;
        _enterStep();
    }

    function _enterStep() {
        _clearFlash();
        _stepComplete = false;

        var step = _steps[_currentStep];

        if (step.onEnter) {
            step.onEnter();
        }

        if (step.flash) {
            _flashElement(step.flash);
        }

        _refreshBox();
    }

    // ── CSS injection ──

    function _injectCSS() {
        var style = document.createElement('style');
        style.textContent = '@keyframes tutFlash { 0%,100% { box-shadow: 0 0 8px 2px rgba(255,220,0,0.7); } 50% { box-shadow: 0 0 20px 6px rgba(255,220,0,1); } } .tutorial-flash { animation: tutFlash 1s infinite !important; z-index: 999; position: relative; }';
        document.head.appendChild(style);
    }

    // ── Public API ──

    return {
        init: function() {
            var settings = _loadSettings();
            if (!settings.tutorialEnabled) return;

            _defineSteps();
            _injectCSS();
            _currentStep = 0;
            _stepComplete = false;
            _initialCounts = {};
            _active = true;

            _createBox();
            _enterStep();
        },

        update: function() {
            if (!_active) return;

            var step = _steps[_currentStep];
            if (step.type !== 'interactive') return;
            if (_stepComplete) return;

            if (step.check && step.check()) {
                _stepComplete = true;
                _refreshBox();
            }
        },

        close: function() {
            _active = false;
            _clearFlash();

            var settings = _loadSettings();
            settings.tutorialEnabled = false;
            _saveSettings(settings);

            Tutorial.destroy();
        },

        destroy: function() {
            _active = false;
            _clearFlash();
            if (_boxEl && _boxEl.parentNode) {
                _boxEl.parentNode.removeChild(_boxEl);
            }
            _boxEl = null;
        },

        isActive: function() {
            return _active;
        },

        isEnabled: function() {
            var settings = _loadSettings();
            return !!settings.tutorialEnabled;
        },

        setEnabled: function(val) {
            var settings = _loadSettings();
            settings.tutorialEnabled = !!val;
            _saveSettings(settings);
        }
    };
})();
